spring:
  application:
    name: movie-service
  config:
    import: optional:configserver:http://config-service:8888

  cloud:
    config:
      profile: ${PROFILE:dev}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${SENHA_DB:7890123}
    url: jdbc:mysql://db_avaliacao2_movie:3307/avaliacao2_movie?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimeZone=UTC

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  rabbitmq:
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    host: localhost
    port: 5672

eureka:
  instance:
    hostname: eureka-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

queue:
  api-movie:
    name: movieQueue

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

info:
  name: Servico de Filmes
  author: Nelson Kobayashi
  mail: koba.nelson@gmail.com
  severity: Alto

